# Generated by Django 5.0.1 on 2024-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_card', '0003_remove_project_title_remove_skill_name_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
